### ISSUE TITLE
Please upload to CDN

### ISSUE THREAD

**Issue by patarapolw** [highlightjs/highlightjs-vue#3]
I don't really how the specifics on how to do this, but you might consider https://www.jsdelivr.com/ or https://cdnjs.com/

Also, you might update README.md after you have got a CDN.

**Comment by LissetteIbnz** [comment]
Thank you!

You can use jsDelivr and Unpkg.

- https://www.jsdelivr.com/package/npm/highlightjs-vue
- https://unpkg.com/highlightjs-vue
